### ISSUE TITLE
perform bad on unseen classes

### ISSUE THREAD

**Issue by bingnoi** [KU-CVLAB/CAT-Seg#14]
i try to train on my own datasets, it shows not bad on seen classes, but got bad results on unseen classes, mostly got 0 precision. what might be the reason?

**Comment by zsc1220** [comment]
@bingnoi  Excuse me, could you give me some tips about how to train on my own datasets. If possible, it would be so appreciate to provide some code, thank you so much!

**Comment by hsshin98** [comment]
Hi, can you specify what kind of dataset or classes you are dealing with? Also, we released our updated version of CAT-Seg with lots of improvements, so you might try our updated version as well!
