### ISSUE TITLE
SAM + CAT-Seg details

### ISSUE THREAD

**Issue by saikatdutta** [KU-CVLAB/CAT-Seg#15]
Hi, where can I find details of SAM + CAT-Seg? Thanks in advance!

**Comment by hsshin98** [comment]
Hi, the details for SAM + CAT-Seg is not specified in our paper as we devised it as an independent demo for applications, but it has similar implementation to this repo: https://github.com/fudan-zvg/Semantic-Segment-Anything.
We first predict open-vocabulary semantic segmentation results with CAT-Seg, and use this to classify the masks from SAM. This is done by considering the majority class in terms of number of pixels within the SAM mask as the predicted class, as in the aforementioned repository.
