### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by jwx15** [KU-CVLAB/CAT-Seg#17]
你的项目要求torch>1.13,且还需要安装detectron2,但detectron2仅支持torch到版本1.10

**Comment by caoql98** [comment]
请问你是怎么解决的，我装不上detectron2了

**Comment by jwx15** [comment]
我就按照作者的命令执行就安装上了

**Comment by caoql98** [comment]
我装到最后就直接报错了

**Comment by jwx15** [comment]
或者你先执行pip install setuptools==59.5.0 wheel==0.41.2

**Comment by jwx15** [comment]
https://detectron2.readthedocs.io/en/latest/tutorials/install.html
或者照着这个里面安装对应的torch和detectron2

**Comment by caoql98** [comment]
是的，我弄好了，就得装pytorch cuda11.7的，我这个pytorch cuda11.6的就过不去，感谢感谢！
