### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by jwx15** [KU-CVLAB/CAT-Seg#18]
demo.py中的from cat_seg import add_mask_former_config是不是应该改成from cat_seg import add_cat_seg_config
而且
def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    add_deeplab_config(cfg)
    add_cat_seg_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg
这里面也改改成add_cat_seg_config(cfg)

**Comment by hsshin98** [comment]
Hi, this seems to be an error in our visualization code, and we updated it accordingly.
Please let us know if you have further problems(we're not sure because we had to run this through a translator.)
Thanks!
