### ISSUE TITLE
fine-tuning clip text encoder?

### ISSUE THREAD

**Issue by lchen1019** [KU-CVLAB/CAT-Seg#19]
![image](https://github.com/KU-CVLAB/CAT-Seg/assets/87420660/acf15011-c962-40fd-a54b-b2029b09ebc3)
![image](https://github.com/KU-CVLAB/CAT-Seg/assets/87420660/05b36212-72dd-4181-a929-409314c50b14)

The framework image shows that the text encoder has been fine-tuned in , but not in the code. Is this picture drawn wrong?

**Comment by Seokju-Cho** [comment]
The code is outdated. Please stay tuned for updates!

**Comment by hsshin98** [comment]
Hi, we just updated the code, and you can check that the same line is updated as "transformer" from "visual", which takes effect on both transformer encoders of CLIP.
Please let us know if you have further questions about the code!

**Comment by lchen1019** [comment]
> Hi, we just updated the code, and you can check that the same line is updated as "transformer" from "visual", which takes effect on both transformer encoders of CLIP. Please let us know if you have further questions about the code!

That's great! Thank you for your excellent work.
