### ISSUE TITLE
Could you please share the training log file?

### ISSUE THREAD

**Issue by dzh19990407** [KU-CVLAB/CAT-Seg#2]
Thanks for your appealing work! Could you please share the training log of the corresponding released model (e.g., CAT-Seg (B))for reference?

**Comment by hsshin98** [comment]
Here's the training log for our ViT-B/16 model, trained with 4x RTX 3090 GPUs!

https://drive.google.com/file/d/1U2Q6Ybr2hBL4XSbUDeGmsFjdY451Ygnx/view?usp=share_link

**Comment by dzh19990407** [comment]
Thank you very much!

**Comment by caddyless** [comment]
Could you please tell me how to open this file? I open it and find all the disordered chars.

**Comment by dzh19990407** [comment]
> Could you please tell me how to open this file? I open it and find all the disordered chars.

You could open it with `tensorboard --logdir=./` after install tensorboard with pip or conda.
