### ISSUE TITLE
About how to visualize the inference results

### ISSUE THREAD

**Issue by DUT-CSJ** [KU-CVLAB/CAT-Seg#22]
Thank you for releasing your great work!
Could you provide the command to visualize the segmentation results on the test dataset using your code and model inference results (json files)?
Looking forward to your reply!

**Comment by hsshin98** [comment]
Hi, for visualization, you can use "demo/demo.py" using the following command line
 python demo/demo.py --config-file path/to/config --output path/to/results --input path/to/input  --opts [OPTS]
 For opts, you can check the command in "eval.sh" for what flags to use.

**Comment by tofutoo** [comment]
> 嗨，对于可视化，您可以使用以下命令行使用“demo/demo.py” python demo/demo.py --config-file path/to/config --output path/to/results --input path/to/input --opts [OPTS] 对于 opts，您可以检查“eval.sh”中的命令以了解要使用的标志。

你好，这里的demo.py中缺少了cannot import name 'add_mask_former_config' from 'cat_seg'，所以我并不能运行，是更新了代码吗，最新的mask我没有找到。

**Comment by DanielChaseButterfield** [comment]
It seems like 'add_mask_former_config' was renamed to 'add_cat_seg_config'. I just ended up renaming it in demo.py.

**Comment by DanielChaseButterfield** [comment]
Also, the run_on_image() call needs to be modified to include a passed text value, or a different error is thrown:
```
text="your,classes,here"
demo.run_on_image(img, text)
```
