### ISSUE TITLE
vocabulary가 다양한 경우

### ISSUE THREAD

**Issue by Pinksaltcaramel** [KU-CVLAB/CAT-Seg#23]
안녕하세요. 저는 막 open-vocabulary semantic segmentation에 관해 공부를 시작한 학생입니다.
CAT-Seg의 논문과 함께 코드를 함께 보고 있는데, 이해하는데 어려움이 있어 도움을 구하기 위해 글 남깁니다.

CAT-Seg의 코드와 논문을 보면 COCO-Stuff의 클래스 개수인 171개의 클래스에 대해서 이미지와 함께 Image와 coco classes(171)간의 Cost volume을 생성하고 학습을 시키는 것으로 보입니다.

하지만 실제로 demo를 돌릴때나 inference할 때는 다양한 개수의 클래스가 들어오는데, 이럴 때는 어떻게 처리하는건가요? 예를 들어 cat, bird, wall, cup을 segmentation할 때와 cat을 segmentation할 때는 class의 개수가 각각 4개, 1개인데, 그러면 cost volume의 shape은 B(batch)x171x24x24가 아니라, Bx4x24x24, Bx1x24x24가 되는건가요? 각각의 cost volume의 channel이 되는데 어떻게 동작이 되는지 궁금합니다.

**Comment by hsshin98** [comment]
안녕하세요,
질문주신 것과 같이 training때는 (B, 1, 171, 24, 24), inference에는 클래스가 4개인 경우 (B, 1, 4, 24, 24)로 되며, shape이 변하게 됩니다.
하지만 실질적인 channel은 1로 고정이 되며, 이는 cost volume은 dot product을 통해 얻어지기 때문입니다. 따라서 이 1 channel을 stem layer을 통해 처리하게 되며, cat_seg/modeling/transformer/model.py 파일에 있는 conv1 layer의 input channel은 1로 고정하여 사용합니다. 
가변하는 class개수에 대해서는 N개가 있다고 할 경우 spatial aggregation은 (B*N, C, H, W), class aggregation의 경우 (B*H*W, C, N)로 동작하게 됩니다. Spatial aggregation은 batch로 처리하기 때문에 N이 변하더라도 상관없고, class aggregation은 가변하는 sequence length를 다루기 때문에 transformer를 사용합니다.

**Comment by Pinksaltcaramel** [comment]
안녕하세요 답변 감사드립니다!
가변하는 sequence length이기 때문에 transformer를 사용한다고 말씀해주셨는데
pad_len(256)으로 전체 sequence length(?)를 맞춰준다고 보면 되는걸까요?

**Comment by hsshin98** [comment]
기본적으로 positional encoding을 사용하지 않는 Transformer이기 때문에 길이를 맞춰주지 않아도 동작할 수 있습니다.
하지만 길이를 고정시켜서 처리하는 것이 실험상 더 좋은 결과를 보여서 pad_len을 통해 이를 얼마로 고정시킬지 정할 수 있고, 0으로 주게 될 경우 class 개수만큼을 sequence length로 그대로 사용하게 됩니다.
