### ISSUE TITLE
train on own dataset

### ISSUE THREAD

**Issue by Zhirui86** [KU-CVLAB/CAT-Seg#28]
Could you plz provide more details about how to train on my own dataset rather than detectron2 built-in datasets? It would be greatly appreciated if you could offer concrete modification in files or suggestions on organizing the data format of custom datasets.
Thanks in advance.

**Comment by hsshin98** [comment]
Hi, we haven't tried out custom datasets, but it shouldn't be a problem if it is following the detectron2 format.
For mapping your dataset into the format, perhaps the instructions in the documentations might help(https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html).
Asides that, the only other thing required would be correctly providing the class names for training. 
This can be done by modifying the config file, or also by the command line with:
```MODEL.SEM_SEG_HEAD.TRAIN_CLASS_JSON "path/to/file.json" ```
Thanks!
