### ISSUE TITLE
is swin frozen?

### ISSUE THREAD

**Issue by yxchng** [KU-CVLAB/CAT-Seg#5]
`frozen_stages` (https://github.com/KU-CVLAB/CAT-Seg/blob/main/cat_seg/modeling/backbone/swin.py#L545) does not seem to have been set in your code?

Otherwise, where else in your code freezes swin?

**Comment by hsshin98** [comment]
We freeze the Swin parameters here (https://github.com/KU-CVLAB/CAT-Seg/blob/7b5e7a53a51c364feacbd68d0adf27ac651f6557/cat_seg/cat_seg_model.py#L77), setting requires_grad = False as backbone_multiplier is given as 0.0 for Swin.
