### ISSUE TITLE
How do you obtain the visualization result in Figure 3?

### ISSUE THREAD

**Issue by yxchng** [KU-CVLAB/CAT-Seg#6]
![Screenshot from 2023-07-19 21-16-08](https://github.com/KU-CVLAB/CAT-Seg/assets/10518587/89bf8251-27c8-4cc1-809b-16b57712eb5e)

CLIP cost volume should be of dimension 24x24. How do you manage to get cost volume of such a high resolution. It does not look like 24x24. Do you mind sharing the code to reproduce this figure?

Thanks.

**Comment by hsshin98** [comment]
For the aggregated cost volume, we show the output of our model, hence has a higher resolution of 96x96. We simply apply bilinear upsampling to overlay with the image.

I don't have the code at the moment, but the visualized figures are normalized with min-max with some scaling for visual clarity, as the model output does not necessarily match the scale with the initial cost volume. This would probably be enough to reproduce the figure, but please let me know if you need more details.
