### ISSUE TITLE
Prepare data for PC-459

### ISSUE THREAD

**Issue by xb534** [KU-CVLAB/CAT-Seg#9]
The link provided for PC-459 https://www.cs.stanford.edu/~roozbeh/pascal-context/trainval.tar.gz is no longer valid. After searching, I found an alternative link [https://roozbehm .info/pascal-context/trainval.tar.gz](https://roozbehm.info/pascal-context/trainval.tar.gz).

**Comment by hsshin98** [comment]
Sorry for the late reply! Thanks for providing an alternative link, and we updated accordingly.

**Comment by zzz-0930** [comment]
您好，能否发一份PC-459数据集中的 prepare_pascal_context_459.py文件给我，文中链接里面好像没有
